/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAnalyzerRouteImport } from './routes/_authenticated/analyzer'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeadlinesRouteImport } from './routes/_authenticated/deadlines'
import { Route as AuthenticatedFacultyReviewRouteImport } from './routes/_authenticated/faculty-review'
import { Route as AuthenticatedIndustrialMentorRouteImport } from './routes/_authenticated/industrial-mentor'
import { Route as AuthenticatedMentorHubRouteImport } from './routes/_authenticated/mentor-hub'
import { Route as AuthenticatedMyTeamRouteImport } from './routes/_authenticated/my-team'
import { Route as AuthenticatedPresentationRouteImport } from './routes/_authenticated/presentation'
import { Route as AuthenticatedProblemsRouteImport } from './routes/_authenticated/problems'
import { Route as AuthenticatedProposalRouteImport } from './routes/_authenticated/proposal'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated/recommendations'
import { Route as AuthenticatedRepositoryRouteImport } from './routes/_authenticated/repository'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedShortlistRouteImport } from './routes/_authenticated/shortlist'
import { Route as AuthenticatedSimilarityRouteImport } from './routes/_authenticated/similarity'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated/submissions'
import { Route as AuthenticatedTeamRegistrationRouteImport } from './routes/_authenticated/team-registration'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as ApiPublicHooksCycleSyncRouteImport } from './routes/api/public/hooks/cycle-sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyzerRoute = AuthenticatedAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeadlinesRoute = AuthenticatedDeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacultyReviewRoute =
  AuthenticatedFacultyReviewRouteImport.update({
    id: '/faculty-review',
    path: '/faculty-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustrialMentorRoute =
  AuthenticatedIndustrialMentorRouteImport.update({
    id: '/industrial-mentor',
    path: '/industrial-mentor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorHubRoute = AuthenticatedMentorHubRouteImport.update({
  id: '/mentor-hub',
  path: '/mentor-hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyTeamRoute = AuthenticatedMyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPresentationRoute =
  AuthenticatedPresentationRouteImport.update({
    id: '/presentation',
    path: '/presentation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProblemsRoute = AuthenticatedProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProposalRoute = AuthenticatedProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepositoryRoute = AuthenticatedRepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShortlistRoute = AuthenticatedShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimilarityRoute = AuthenticatedSimilarityRouteImport.update({
  id: '/similarity',
  path: '/similarity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamRegistrationRoute =
  AuthenticatedTeamRegistrationRouteImport.update({
    id: '/team-registration',
    path: '/team-registration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicHooksCycleSyncRoute = ApiPublicHooksCycleSyncRouteImport.update({
  id: '/api/public/hooks/cycle-sync',
  path: '/api/public/hooks/cycle-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/analyzer': typeof AuthenticatedAnalyzerRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deadlines': typeof AuthenticatedDeadlinesRoute
  '/faculty-review': typeof AuthenticatedFacultyReviewRoute
  '/industrial-mentor': typeof AuthenticatedIndustrialMentorRoute
  '/mentor-hub': typeof AuthenticatedMentorHubRoute
  '/my-team': typeof AuthenticatedMyTeamRoute
  '/presentation': typeof AuthenticatedPresentationRoute
  '/problems': typeof AuthenticatedProblemsRoute
  '/proposal': typeof AuthenticatedProposalRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/repository': typeof AuthenticatedRepositoryRoute
  '/results': typeof AuthenticatedResultsRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shortlist': typeof AuthenticatedShortlistRoute
  '/similarity': typeof AuthenticatedSimilarityRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/team-registration': typeof AuthenticatedTeamRegistrationRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/cycle-sync': typeof ApiPublicHooksCycleSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/analyzer': typeof AuthenticatedAnalyzerRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deadlines': typeof AuthenticatedDeadlinesRoute
  '/faculty-review': typeof AuthenticatedFacultyReviewRoute
  '/industrial-mentor': typeof AuthenticatedIndustrialMentorRoute
  '/mentor-hub': typeof AuthenticatedMentorHubRoute
  '/my-team': typeof AuthenticatedMyTeamRoute
  '/presentation': typeof AuthenticatedPresentationRoute
  '/problems': typeof AuthenticatedProblemsRoute
  '/proposal': typeof AuthenticatedProposalRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/repository': typeof AuthenticatedRepositoryRoute
  '/results': typeof AuthenticatedResultsRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shortlist': typeof AuthenticatedShortlistRoute
  '/similarity': typeof AuthenticatedSimilarityRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/team-registration': typeof AuthenticatedTeamRegistrationRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/cycle-sync': typeof ApiPublicHooksCycleSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/analyzer': typeof AuthenticatedAnalyzerRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deadlines': typeof AuthenticatedDeadlinesRoute
  '/_authenticated/faculty-review': typeof AuthenticatedFacultyReviewRoute
  '/_authenticated/industrial-mentor': typeof AuthenticatedIndustrialMentorRoute
  '/_authenticated/mentor-hub': typeof AuthenticatedMentorHubRoute
  '/_authenticated/my-team': typeof AuthenticatedMyTeamRoute
  '/_authenticated/presentation': typeof AuthenticatedPresentationRoute
  '/_authenticated/problems': typeof AuthenticatedProblemsRoute
  '/_authenticated/proposal': typeof AuthenticatedProposalRoute
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/repository': typeof AuthenticatedRepositoryRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shortlist': typeof AuthenticatedShortlistRoute
  '/_authenticated/similarity': typeof AuthenticatedSimilarityRoute
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/_authenticated/team-registration': typeof AuthenticatedTeamRegistrationRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/cycle-sync': typeof ApiPublicHooksCycleSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/admin'
    | '/analytics'
    | '/analyzer'
    | '/announcements'
    | '/approvals'
    | '/dashboard'
    | '/deadlines'
    | '/faculty-review'
    | '/industrial-mentor'
    | '/mentor-hub'
    | '/my-team'
    | '/presentation'
    | '/problems'
    | '/proposal'
    | '/recommendations'
    | '/repository'
    | '/results'
    | '/sessions'
    | '/settings'
    | '/shortlist'
    | '/similarity'
    | '/submissions'
    | '/team-registration'
    | '/admin/students'
    | '/admin/'
    | '/api/public/hooks/cycle-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/analytics'
    | '/analyzer'
    | '/announcements'
    | '/approvals'
    | '/dashboard'
    | '/deadlines'
    | '/faculty-review'
    | '/industrial-mentor'
    | '/mentor-hub'
    | '/my-team'
    | '/presentation'
    | '/problems'
    | '/proposal'
    | '/recommendations'
    | '/repository'
    | '/results'
    | '/sessions'
    | '/settings'
    | '/shortlist'
    | '/similarity'
    | '/submissions'
    | '/team-registration'
    | '/admin/students'
    | '/admin'
    | '/api/public/hooks/cycle-sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/analyzer'
    | '/_authenticated/announcements'
    | '/_authenticated/approvals'
    | '/_authenticated/dashboard'
    | '/_authenticated/deadlines'
    | '/_authenticated/faculty-review'
    | '/_authenticated/industrial-mentor'
    | '/_authenticated/mentor-hub'
    | '/_authenticated/my-team'
    | '/_authenticated/presentation'
    | '/_authenticated/problems'
    | '/_authenticated/proposal'
    | '/_authenticated/recommendations'
    | '/_authenticated/repository'
    | '/_authenticated/results'
    | '/_authenticated/sessions'
    | '/_authenticated/settings'
    | '/_authenticated/shortlist'
    | '/_authenticated/similarity'
    | '/_authenticated/submissions'
    | '/_authenticated/team-registration'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/'
    | '/api/public/hooks/cycle-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksCycleSyncRoute: typeof ApiPublicHooksCycleSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analyzer': {
      id: '/_authenticated/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AuthenticatedAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deadlines': {
      id: '/_authenticated/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof AuthenticatedDeadlinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faculty-review': {
      id: '/_authenticated/faculty-review'
      path: '/faculty-review'
      fullPath: '/faculty-review'
      preLoaderRoute: typeof AuthenticatedFacultyReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industrial-mentor': {
      id: '/_authenticated/industrial-mentor'
      path: '/industrial-mentor'
      fullPath: '/industrial-mentor'
      preLoaderRoute: typeof AuthenticatedIndustrialMentorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor-hub': {
      id: '/_authenticated/mentor-hub'
      path: '/mentor-hub'
      fullPath: '/mentor-hub'
      preLoaderRoute: typeof AuthenticatedMentorHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-team': {
      id: '/_authenticated/my-team'
      path: '/my-team'
      fullPath: '/my-team'
      preLoaderRoute: typeof AuthenticatedMyTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presentation': {
      id: '/_authenticated/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof AuthenticatedPresentationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problems': {
      id: '/_authenticated/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof AuthenticatedProblemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposal': {
      id: '/_authenticated/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof AuthenticatedProposalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repository': {
      id: '/_authenticated/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof AuthenticatedRepositoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shortlist': {
      id: '/_authenticated/shortlist'
      path: '/shortlist'
      fullPath: '/shortlist'
      preLoaderRoute: typeof AuthenticatedShortlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/similarity': {
      id: '/_authenticated/similarity'
      path: '/similarity'
      fullPath: '/similarity'
      preLoaderRoute: typeof AuthenticatedSimilarityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-registration': {
      id: '/_authenticated/team-registration'
      path: '/team-registration'
      fullPath: '/team-registration'
      preLoaderRoute: typeof AuthenticatedTeamRegistrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/hooks/cycle-sync': {
      id: '/api/public/hooks/cycle-sync'
      path: '/api/public/hooks/cycle-sync'
      fullPath: '/api/public/hooks/cycle-sync'
      preLoaderRoute: typeof ApiPublicHooksCycleSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAnalyzerRoute: typeof AuthenticatedAnalyzerRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeadlinesRoute: typeof AuthenticatedDeadlinesRoute
  AuthenticatedFacultyReviewRoute: typeof AuthenticatedFacultyReviewRoute
  AuthenticatedIndustrialMentorRoute: typeof AuthenticatedIndustrialMentorRoute
  AuthenticatedMentorHubRoute: typeof AuthenticatedMentorHubRoute
  AuthenticatedMyTeamRoute: typeof AuthenticatedMyTeamRoute
  AuthenticatedPresentationRoute: typeof AuthenticatedPresentationRoute
  AuthenticatedProblemsRoute: typeof AuthenticatedProblemsRoute
  AuthenticatedProposalRoute: typeof AuthenticatedProposalRoute
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
  AuthenticatedRepositoryRoute: typeof AuthenticatedRepositoryRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShortlistRoute: typeof AuthenticatedShortlistRoute
  AuthenticatedSimilarityRoute: typeof AuthenticatedSimilarityRoute
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedTeamRegistrationRoute: typeof AuthenticatedTeamRegistrationRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAnalyzerRoute: AuthenticatedAnalyzerRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeadlinesRoute: AuthenticatedDeadlinesRoute,
  AuthenticatedFacultyReviewRoute: AuthenticatedFacultyReviewRoute,
  AuthenticatedIndustrialMentorRoute: AuthenticatedIndustrialMentorRoute,
  AuthenticatedMentorHubRoute: AuthenticatedMentorHubRoute,
  AuthenticatedMyTeamRoute: AuthenticatedMyTeamRoute,
  AuthenticatedPresentationRoute: AuthenticatedPresentationRoute,
  AuthenticatedProblemsRoute: AuthenticatedProblemsRoute,
  AuthenticatedProposalRoute: AuthenticatedProposalRoute,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
  AuthenticatedRepositoryRoute: AuthenticatedRepositoryRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShortlistRoute: AuthenticatedShortlistRoute,
  AuthenticatedSimilarityRoute: AuthenticatedSimilarityRoute,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedTeamRegistrationRoute: AuthenticatedTeamRegistrationRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksCycleSyncRoute: ApiPublicHooksCycleSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
